name: Tagging

on:
  push:
    branches: ["dev"]

jobs:
  tagging:
    permissions:
      contents: write
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - uses: TriPSs/conventional-changelog-action@v3
        name: Changelog
        id: changelog
        with:
          git-user-name: "Antonio Donis"
          git-user-email: "antoniojosedonishung@gmail.com"
          git-message: "[ci skip] chore(release): {version}"
          git-branch: "dev"
          version-file: "version.json"