name: Test

on:
  pull_request:
    branches: ["dev"]

jobs:
  test:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3

      - name: Set up docker environment
        run: docker-compose up -d
      
      - uses: actions/setup-python@v4
        with:
          python-version: '3.11' 
          cache: 'pip'

      - name: Install dependencies
        run: pip install -r requirements.txt
      
      - name: Run tests
        run: pytest
      
      - name: Clean docker environment
        run: docker compose -f docker-compose.dev.yaml down --rmi all -v --remove-orphans